/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminPendingRouteImport } from './routes/admin/pending'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CheckoutPageIdRouteImport } from './routes/checkout/$pageId'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardFavoritesRouteImport } from './routes/dashboard/favorites'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardPagesRouteImport } from './routes/dashboard/pages'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DemoSlugRouteImport } from './routes/demo/$slug'
import { Route as EditorPageIdRouteImport } from './routes/editor/$pageId'
import { Route as EditorNewRouteImport } from './routes/editor/new'
import { Route as PSlugRouteImport } from './routes/p/$slug'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates/$slug'
import { Route as EditorTemplateTemplateIdRouteImport } from './routes/editor/template/$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPageIdRoute = CheckoutPageIdRouteImport.update({
  id: '/checkout/$pageId',
  path: '/checkout/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFavoritesRoute = DashboardFavoritesRouteImport.update({
  id: '/dashboard/favorites',
  path: '/dashboard/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPagesRoute = DashboardPagesRouteImport.update({
  id: '/dashboard/pages',
  path: '/dashboard/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSlugRoute = DemoSlugRouteImport.update({
  id: '/demo/$slug',
  path: '/demo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorPageIdRoute = EditorPageIdRouteImport.update({
  id: '/editor/$pageId',
  path: '/editor/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/templates/$slug',
  path: '/templates/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTemplateTemplateIdRoute =
  EditorTemplateTemplateIdRouteImport.update({
    id: '/editor/template/$templateId',
    path: '/editor/template/$templateId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$pageId': typeof CheckoutPageIdRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/editor/new': typeof EditorNewRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/editor/template/$templateId': typeof EditorTemplateTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$pageId': typeof CheckoutPageIdRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/editor/new': typeof EditorNewRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/editor/template/$templateId': typeof EditorTemplateTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/$pageId': typeof CheckoutPageIdRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/pages': typeof DashboardPagesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/demo/$slug': typeof DemoSlugRoute
  '/editor/$pageId': typeof EditorPageIdRoute
  '/editor/new': typeof EditorNewRoute
  '/p/$slug': typeof PSlugRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/editor/template/$templateId': typeof EditorTemplateTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/pricing'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/pending'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/$pageId'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/notifications'
    | '/dashboard/pages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/demo/$slug'
    | '/editor/$pageId'
    | '/editor/new'
    | '/p/$slug'
    | '/templates/$slug'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/templates/'
    | '/editor/template/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/pricing'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/pending'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/$pageId'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/notifications'
    | '/dashboard/pages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/demo/$slug'
    | '/editor/$pageId'
    | '/editor/new'
    | '/p/$slug'
    | '/templates/$slug'
    | '/admin'
    | '/blog'
    | '/dashboard'
    | '/templates'
    | '/editor/template/$templateId'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/pricing'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/pending'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/blog/$slug'
    | '/checkout/$pageId'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/favorites'
    | '/dashboard/notifications'
    | '/dashboard/pages'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/demo/$slug'
    | '/editor/$pageId'
    | '/editor/new'
    | '/p/$slug'
    | '/templates/$slug'
    | '/admin/'
    | '/blog/'
    | '/dashboard/'
    | '/templates/'
    | '/editor/template/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CheckoutPageIdRoute: typeof CheckoutPageIdRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPagesRoute: typeof DashboardPagesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DemoSlugRoute: typeof DemoSlugRoute
  EditorPageIdRoute: typeof EditorPageIdRoute
  EditorNewRoute: typeof EditorNewRoute
  PSlugRoute: typeof PSlugRoute
  TemplatesSlugRoute: typeof TemplatesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  EditorTemplateTemplateIdRoute: typeof EditorTemplateTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$pageId': {
      id: '/checkout/$pageId'
      path: '/checkout/$pageId'
      fullPath: '/checkout/$pageId'
      preLoaderRoute: typeof CheckoutPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pages': {
      id: '/dashboard/pages'
      path: '/dashboard/pages'
      fullPath: '/dashboard/pages'
      preLoaderRoute: typeof DashboardPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$slug': {
      id: '/demo/$slug'
      path: '/demo/$slug'
      fullPath: '/demo/$slug'
      preLoaderRoute: typeof DemoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$pageId': {
      id: '/editor/$pageId'
      path: '/editor/$pageId'
      fullPath: '/editor/$pageId'
      preLoaderRoute: typeof EditorPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/templates/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/template/$templateId': {
      id: '/editor/template/$templateId'
      path: '/editor/template/$templateId'
      fullPath: '/editor/template/$templateId'
      preLoaderRoute: typeof EditorTemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  BlogSlugRoute: BlogSlugRoute,
  CheckoutPageIdRoute: CheckoutPageIdRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPagesRoute: DashboardPagesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DemoSlugRoute: DemoSlugRoute,
  EditorPageIdRoute: EditorPageIdRoute,
  EditorNewRoute: EditorNewRoute,
  PSlugRoute: PSlugRoute,
  TemplatesSlugRoute: TemplatesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  EditorTemplateTemplateIdRoute: EditorTemplateTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
